import type { Question } from '../types';

export const ALL_QUESTIONS: Question[] = [
  // Page 1 - Third Date
  { question: "When was the last time a scent reminded you of a childhood memory? Share that story with me.", mode: "Third Date" },
  { question: "When do you feel the most insecure?", mode: "Third Date" },
  { question: "If you could relive one year of your life, which would it be and why?", mode: "Third Date" },
  { question: "What's the most thrilling thing you've ever done?", mode: "Third Date" },
  { question: "What's something you wish you were really good at?", mode: "Third Date" },
  { question: "What's been the best thing in your life to happen so far?", mode: "Third Date" },
  { question: "Both write down your three most important values in life. Compare.", mode: "Third Date" },
  { question: "Describe yourself in three words.", mode: "Third Date" },
  { question: "What does your dream house look like? Where is it?", mode: "Third Date" },
  { question: "If you could give one piece of advice to your younger self, what would it be?", mode: "Third Date" },
  { question: "What's one of your favourite childhood memories?", mode: "Third Date" },
  { question: "What book do you think would be beneficial for me to read?", mode: "Third Date" },
  { question: "Share something you find irresistibly attractive that might surprise me.", mode: "Third Date" },
  { question: "If you had to pick an animal to describe your skills in bed, what would it be and why?", mode: "Third Date" },
  { question: "What would you do if you were invisible for a day?", mode: "Third Date" },
  { question: "If you could instantly gain one skill in the bedroom, what would it be?", mode: "Third Date" },
  { question: "Describe your ideal morning routine.", mode: "Third Date" },
  { question: "How have you changed in the past five years?", mode: "Third Date" },

  // Page 2 - Third Date, Second Date
  { question: "What did you learn about money from your parents?", mode: "Third Date" },
  { question: "What's your worst habit?", mode: "Third Date" },
  { question: "What is your favorite thing that I wear?", mode: "Third Date" },
  { question: "Where are three places you've thought about having sex?", mode: "Third Date" },
  { question: "What's one of your secret sexual fantasies?", mode: "Third Date" },
  { question: "What is your most terrible memory?", mode: "Third Date" },
  { question: "What is your most cherished memory?", mode: "Third Date" },
  { question: "What's a deeply held dream you have?", mode: "Second Date" },
  { question: "What does your five year plan look like?", mode: "Second Date" },
  { question: "What were the major turning points in your life?", mode: "Second Date", category: "Life" },
  { question: "What do you think are my best qualities?", mode: "Second Date", category: "About You" },
  { question: "What lie have you told yourself so much that you now believe it?", mode: "Second Date", category: "About You" },
  { question: "Is there anyone you look up to? Who and why?", mode: "Second Date" },
  { question: "What's your biggest fear?", mode: "Second Date" },
  { question: "How do you define success?", mode: "Second Date" },
  { question: "Are you more like one of your parents? Which one?", mode: "Second Date" },
  { question: "What's something you wish I did more often?", mode: "Second Date" },
  { question: "What were you like as a student?", mode: "Second Date" },
  { question: "What's the craziest thing you've ever done and you would do again?", mode: "Second Date" },
  { question: "What would you tell yourself if you could go back then years ago?", mode: "Second Date" },
  { question: "If you could make one rule for our date, what would it be?", mode: "Second Date" },
  { question: "If we were in a movie right now, what would be our perfect scene?", mode: "Second Date" },

  // Page 3 - Second Date, First Date
  { question: "What's the most embarrassing that has happened to you?", mode: "Second Date" },
  { question: "What did you want to be when you grew up?", mode: "Second Date" },
  { question: "Tell a story of how a stranger changed your life.", mode: "Second Date" },
  { question: "Which personal accomplishment are you most proud of? Why?", mode: "Second Date" },
  { question: "What charity or social issue is most important to you? Why?", mode: "Second Date" },
  { question: "What you really need to understand about me and sex is...", mode: "Second Date" },
  { question: "What part of your body do you worry turns me off?", mode: "Second Date" },
  { question: "What kind of power dynamics excite you?", mode: "Second Date" },
  { question: "How do you hope your life will change in the next three years?", mode: "Second Date" },
  { question: "List five items on your bucket list.", mode: "Second Date" },
  { question: "If you could wake up tomorrow having gained one skill to perfection, what would it be?", mode: "Second Date" },
  { question: "How long do you know your best friend?", mode: "First Date" },
  { question: "What's one thing that instantly makes you feel a connection with someone?", mode: "First Date", category: "About You" },
  { question: "What's your spirit animal? Why?", mode: "First Date", category: "About You" },
  { question: "What's your favourite meal? Why?", mode: "First Date", category: "About You" },
  { question: "Which book has impacted your life the most?", mode: "First Date", category: "Experience" },
  { question: "Is there a song that immediately lifts your mood? Which one?", mode: "First Date" },
  { question: "What gives you the ick, no matter how attractive they are?", mode: "First Date" },
  { question: "What are your goals for this year?", mode: "First Date" },
  { question: "What is your favorite feature about yourself?", mode: "First Date" },
  { question: "How do you like to spend your alone time?", mode: "First Date" },

  // Page 4 - First Date, Love Birds
  { question: "If there was a Google review for dating you, what would it say?", mode: "First Date" },
  { question: "What's the funniest way someone has tried to seduce you?", mode: "First Date" },
  { question: "On a scale of 1-10, how comfortable are you with public displays of affection? Explain.", mode: "First Date" },
  { question: "Name three things you like about your partner.", mode: "First Date" },
  { question: "What is your love language for both giving and receiving love? (Physical Touch, Words of Affirmation, Quality Time, Acts of Service, Receiving Gifts).", mode: "First Date" },
  { question: "What do you value most in a friendship?", mode: "First Date" },
  { question: "Do you consider yourself more submissive or dominant?", mode: "First Date" },
  { question: "What was your first impression of me? Digital and in real life.", mode: "First Date" },
  { question: "If you could instantly attain three skills, what would they be?", mode: "First Date" },
  { question: "If you could change anything about your upbringing, what would it be?", mode: "First Date" },
  { question: "What are you most grateful for in your life?", mode: "First Date" },
  { question: "What are three things you believe we have in common?", mode: "First Date" },
  { question: "Do you have a secret hunch about how you will die?", mode: "First Date" },
  { question: "Describe your idea of a perfect day.", mode: "First Date" },
  { question: "Would you want to be famous, and if so, in what way?", mode: "First Date" },
  { question: "On a scale of 1 to 10, how would you rate yourself?", mode: "First Date" },
  { question: "If you received €10,000, how would you spend it?", mode: "First Date" },
  { question: "What was the most recent experience that made you feel closer to me?", mode: "Love Birds" },
  { question: "What is a compromise you've had to make since meeting me?", mode: "Love Birds" },

  // Page 5 - Love Birds
  { question: "What feelings are hard for you to communicate? How can I make it easier?", mode: "Love Birds" },
  { question: "What's a deeply held dream you have?", mode: "Love Birds" },
  { question: "What's a need you have that will allow you to shine more in life?", mode: "Love Birds" },
  { question: "Do you ever feel jealous if you see me talking to other attractive people?", mode: "Love Birds" },
  { question: "What's the best thing you inherited from each of your parents?", mode: "Love Birds" },
  { question: "Can you remember what I was wearing when we first met?", mode: "Love Birds" },
  { question: "Is there someone to whom you owe an apology? What for?", mode: "Love Birds", category: "Experience" },
  { question: "When you experience stress how do you like to be supported?", mode: "Love Birds", category: "Life" },
  { question: "Where is the most beautiful place you have ever been?", mode: "Love Birds" },
  { question: "What's something you love about your hometown?", mode: "Love Birds" },
  { question: "Express gratitude for the person you're with. Why are you thankful for them?", mode: "Love Birds" },
  { question: "Where is your favorite place to visit together?", mode: "Love Birds" },
  { question: "What boundaries can we set to protect our relationship and communication from being damaged by technology?", mode: "Love Birds" },
  { question: "What do you look forward to every day?", mode: "Love Birds" },
  { question: "What's something I introduced you to that you now enjoy?", mode: "Love Birds" },
  { question: "Is there something you've always wanted to do? What's stopped you?", mode: "Love Birds" },
  { question: "What has been the best part of your day so far?", mode: "Love Birds" },

  // Page 6 - Love Birds
  { question: "What helps you calm down when you're stressed or upset?", mode: "Love Birds" },
  { question: "Describe your ideal date in three words.", mode: "Love Birds" },
  { question: "What's a lesson you learned the hard way?", mode: "Love Birds" },
  { question: "How do you like to be comforted when you're feeling down?", mode: "Love Birds" },
  { question: "What's something you've always wanted to try but haven't yet?", mode: "Love Birds" },
  { question: "Describe a turn-on you haven't shared with me yet.", mode: "Love Birds" },
  { question: "How many times do you want to be intimate each week?", mode: "Love Birds" },
  { question: "What's your favourite time of day for sex?", mode: "Love Birds" },
  { question: "Which celebrity would you choose if you had a free pass to sleep with anyone?", mode: "Love Birds" },
  { question: "If a crystal ball could tell you the truth about yourself, your life, the future or anything else, what would you want to know?", mode: "Love Birds" },
  { question: "If we decided not to have actual intercourse, but still wanted to do something sexual, what might we do?", mode: "Love Birds" },
  { question: "What's one thing you'd like to get better at over the next year?", mode: "Love Birds" },
  { question: "If you could choose any city to live in for a year, where would it be and why?", mode: "Love Birds", category: "Life"},
  { question: "What's something you've always wanted to try but haven't yet?", mode: "Love Birds", category: "Life"}
];
