
import { GameMode, Question, QuestionType } from './types';

export const GAME_MODES: { mode: GameMode, description: string }[] = [
    { mode: GameMode.FirstDate, description: "Light & fun icebreakers" },
    { mode: GameMode.SecondDate, description: "Slightly deeper prompts" },
    { mode: GameMode.ThirdDate, description: "Emotional and intimate" },
    { mode: GameMode.LoveBirds, description: "For established couples" },
    { mode: GameMode.GroupMode, description: "Spicy, humorous & open-ended" },
];

export const QUESTIONS: Question[] = [
    // First Date
    { text: "How long do you know your best friend?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "What's one thing that instantly makes you feel a connection with someone?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "Would you rather have amazing physical chemistry but zero music taste compatibility, or the other way around?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "What's your spirit animal? Why?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "What's your favourite meal? Why?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "Which book has impacted your life the most?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "Is there a song that immediately lifts your mood? Which one?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "What gives you the ick, no matter how attractive they are?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "What are your goals for this year?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "What is your favorite feature about yourself?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "How do you like to spend your alone time?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "If there was a Google review for dating you, what would it say?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "What's the funniest way someone has tried to seduce you?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "On a scale of 1-10, how comfortable are you with public displays of affection? Explain.", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "Name three things you like about your partner.", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "What is your love language for both giving and receiving love? (Physical Touch, Words of Affirmation, Quality Time, Acts of Service, Receiving Gifts)", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "What do you value most in a friendship?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "Do you consider yourself more submissive or dominant?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "What was your first impression of me? Digital and in real life.", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "If you could instantly attain three skills, what would they be?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "If you could change anything about your upbringing, what would it be?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "What are you most grateful for in your life?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "What are three things you believe we have in common?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "Describe your idea of a perfect day.", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "Would you want to be famous, and if so, in what way?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "On a scale of 1 to 10, how would you rate yourself?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "If you received €10,000, how would you spend it?", mode: GameMode.FirstDate, type: QuestionType.Question },

    // Newly added First Date icebreakers
    { text: "What’s something weirdly specific that turns you on?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "What’s more attractive to you: ambition or kindness?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "What food would immediately make you leave a date if I ordered it?", mode: GameMode.FirstDate, type: QuestionType.Question },
    { text: "If your life had background music, what song would be playing right now?", mode: GameMode.FirstDate, type: QuestionType.Question },

    // Second Date
    { text: "What's a deeply held dream you have?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "What does your five year plan look like?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "What were the major turning points in your life?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "What do you think are my best qualities?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "What lie have you told yourself so much that you now believe it?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "Is there anyone you look up to? Who and why?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "What's your biggest fear?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "How do you define success?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "Are you more like one of your parents? Which one?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "What's something you wish I did more often?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "What were you like as a student?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "What's the craziest thing you've ever done and you would do again?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "What would you tell yourself if you could go back ten years ago?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "If you could make one rule for our date, what would it be?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "If we were in a movie right now, what would be our perfect scene?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "What's the most embarrassing that has happened to you?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "What did you want to be when you grew up?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "Tell a story of how a stranger changed your life.", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "Which personal accomplishment are you most proud of? Why?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "What charity or social issue is most important to you? Why?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "What you really need to understand about me and sex is…", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "What part of your body do you worry turns me off?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "What kind of power dynamics excite you?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "How do you hope your life will change in the next three years?", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "List five items on your bucket list.", mode: GameMode.SecondDate, type: QuestionType.Question },
    { text: "If you could wake up tomorrow having gained one skill to perfection, what would it be?", mode: GameMode.SecondDate, type: QuestionType.Question },

    // Third Date
    { text: "When was the last time a scent reminded you of a childhood memory? Share that story with me.", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "When do you feel the most insecure?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "If you could relive one year of your life, which would it be and why?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "What's the most thrilling thing you've ever done?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "What's something you wish you were really good at?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "What's been the best thing in your life to happen so far?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "Both write down your three most important values in life. Compare.", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "Describe yourself in three words.", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "What does your dream house look like? Where is it?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "If you could give one piece of advice to your younger self, what would it be?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "What's one of your favourite childhood memories?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "What book do you think would be beneficial for me to read?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "Share something you find irresistibly attractive that might surprise me.", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "If you had to pick an animal to describe your skills in bed, what would it be and why?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "What would you do if you were invisible for a day?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "If you could instantly gain one skill in the bedroom, what would it be?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "Describe your ideal morning routine.", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "How have you changed in the past five years?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "What did you learn about money from your parents?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "What's your worst habit?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "What is your favorite thing that I wear?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "Where are three places you've thought about having sex?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "What's one of your secret sexual fantasies?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "What is your most terrible memory?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    { text: "What is your most cherished memory?", mode: GameMode.ThirdDate, type: QuestionType.Question },
    
    // Love Birds
    { text: "What was the most recent experience that made you feel closer to me?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "What is a compromise you've had to make since meeting me?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "What feelings are hard for you to communicate? How can I make it easier?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "What's a deeply held dream you have?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "What's a need you have that will allow you to shine more in life?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "Do you ever feel jealous if you see me talking to other attractive people?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "What's the best thing you inherited from each of your parents?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "Can you remember what I was wearing when we first met?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "Is there someone to whom you owe an apology? What for?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "When you experience stress how do you like to be supported?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "Where is the most beautiful place you have ever been?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "What's something you love about your hometown?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "Express gratitude for the person you're with. Why are you thankful for them?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "Where is your favorite place to visit together?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "What boundaries can we set to protect our relationship and communication from being damaged by technology?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "What do you look forward to every day?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "What's something I introduced you to that you now enjoy?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "Is there something you've always wanted to do? What's stopped you?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "What has been the best part of your day so far?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "What helps you calm down when you're stressed or upset?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "Describe your ideal date in three words.", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "What's a lesson you learned the hard way?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "How do you like to be comforted when you're feeling down?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "What's something you've always wanted to try but haven't yet?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "Describe a turn-on you haven't shared with me yet.", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "How many times do you want to be intimate each week?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "What's your favourite time of day for sex?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "Which celebrity would you choose if you had a free pass to sleep with anyone?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "If a crystal ball could tell you the truth about yourself, your life, the future or anything else, what would you want to know?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "If we decided not to have actual intercourse, but still wanted to do something sexual, what might we do?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    { text: "What's one thing you'd like to get better at over the next year?", mode: GameMode.LoveBirds, type: QuestionType.Question },
    
    // Group Mode
    { text: "If you could choose any city to live in for a year, where would it be and why?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "What's something you've always wanted to try but haven't yet?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "If you had to trade lives with someone in this room, who would it be and why?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "What's a secret you've never told anyone here?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "What's the most illegal thing you've ever done?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "Who in this room would survive the longest in a zombie apocalypse?", mode: GameMode.GroupMode, type: QuestionType.Question },

    // Newly added Friends Mode questions
    { text: "What’s the most petty reason you’ve ever ghosted someone?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "You get one free slap - who and why?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "What’s a red flag you’re weirdly into?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "What would you never admit on your main instagram but lowkey want to share?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "Who here would you trust to wingman you - and who absolutely not?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "Who here would soft launch someone after one good date?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "Who’s most likely to have a secret situationship no one knows about?", mode: GameMode.GroupMode, type: QuestionType.Question },
 
    // Would You Rather Questions
    { text: "Would you rather have the ability to read minds or be invisible?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "Would you rather have your browser history made public or your bank account balance displayed above your head?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "Would you rather only be able to whisper or only be able to shout for the rest of your life?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "Would you rather fight one horse-sized duck or 100 duck-sized horses?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "Would you rather know the date of your death or the cause of your death?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "Would you rather have unlimited money but no close relationships, or amazing relationships but always struggle financially?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "Would you rather always be 10 minutes late or 20 minutes early to everything?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "Would you rather have to sing everything you say or dance everywhere you go?", mode: GameMode.GroupMode, type: QuestionType.Question },
    
    // Rating/Scaling Questions
    { text: "On a scale of 1-10, how likely are you to survive a horror movie? Explain your strategy.", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "Rate everyone in this room from 1-10 on who would make the best reality TV star. Explain why.", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "On a scale of 1-10, how much of a risk-taker are you? Give an example.", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "Rate your cooking skills from 1-10. What's the most impressive dish you can make?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "On a scale of 1-10, how good are you at keeping secrets? Has anyone here tested this?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "Rate your texting game from 1-10. Are you a quick replier or do you leave people on read?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "On a scale of 1-10, how competitive are you? What brings out your competitive side the most?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "Rate your dance moves from 1-10. Show us your signature move!", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "On a scale of 1-10, how likely are you to eat something that fell on the floor? Does the 5-second rule apply?", mode: GameMode.GroupMode, type: QuestionType.Question },
    { text: "Rate your ability to lie convincingly from 1-10. Tell us a lie right now and see if we can guess!", mode: GameMode.GroupMode, type: QuestionType.Question },
];

export const WILDCARD_QUESTION: Question = {
    text: "Make up your own question!",
    mode: GameMode.FirstDate, // Mode doesn't matter for wildcard
    type: QuestionType.Wildcard,
};

export const INITIAL_WILDCARDS = 3;
